// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gotato/v2/service.proto

package gotatov2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractRequest) Reset() {
	*x = ContractRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRequest) ProtoMessage() {}

func (x *ContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRequest.ProtoReflect.Descriptor instead.
func (*ContractRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{0}
}

type ContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractResponse) Reset() {
	*x = ContractResponse{}
	mi := &file_gotato_v2_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractResponse) ProtoMessage() {}

func (x *ContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractResponse.ProtoReflect.Descriptor instead.
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *ContractResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentsRequest) Reset() {
	*x = AgentsRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentsRequest) ProtoMessage() {}

func (x *AgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentsRequest.ProtoReflect.Descriptor instead.
func (*AgentsRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{2}
}

type AgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []string               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentsResponse) Reset() {
	*x = AgentsResponse{}
	mi := &file_gotato_v2_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentsResponse) ProtoMessage() {}

func (x *AgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentsResponse.ProtoReflect.Descriptor instead.
func (*AgentsResponse) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{3}
}

func (x *AgentsResponse) GetAgents() []string {
	if x != nil {
		return x.Agents
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *CreateSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{5}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Messages      int32                  `protobuf:"varint,5,opt,name=messages,proto3" json:"messages,omitempty"`
	Runs          int32                  `protobuf:"varint,6,opt,name=runs,proto3" json:"runs,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_gotato_v2_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{6}
}

func (x *SessionSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionSummary) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *SessionSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SessionSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SessionSummary) GetMessages() int32 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *SessionSummary) GetRuns() int32 {
	if x != nil {
		return x.Runs
	}
	return 0
}

func (x *SessionSummary) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *SessionSummary) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SessionDocument carries the session.Document as JSON so the adapter never
// redefines the Session schema.
type SessionDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentJson  []byte                 `protobuf:"bytes,1,opt,name=document_json,json=documentJson,proto3" json:"document_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDocument) Reset() {
	*x = SessionDocument{}
	mi := &file_gotato_v2_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDocument) ProtoMessage() {}

func (x *SessionDocument) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDocument.ProtoReflect.Descriptor instead.
func (*SessionDocument) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{7}
}

func (x *SessionDocument) GetDocumentJson() []byte {
	if x != nil {
		return x.DocumentJson
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{8}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSummary      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_gotato_v2_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListSessionsResponse) GetSessions() []*SessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_gotato_v2_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSessionResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type RunRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Agent     string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*RunRequest_Prompt
	//	*RunRequest_ContinueInput
	Input         isRunRequest_Input `protobuf_oneof:"input"`
	Metadata      map[string]string  `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{11}
}

func (x *RunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *RunRequest) GetInput() isRunRequest_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunRequest) GetPrompt() string {
	if x != nil {
		if x, ok := x.Input.(*RunRequest_Prompt); ok {
			return x.Prompt
		}
	}
	return ""
}

func (x *RunRequest) GetContinueInput() *ContinueInput {
	if x != nil {
		if x, ok := x.Input.(*RunRequest_ContinueInput); ok {
			return x.ContinueInput
		}
	}
	return nil
}

func (x *RunRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isRunRequest_Input interface {
	isRunRequest_Input()
}

type RunRequest_Prompt struct {
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3,oneof"`
}

type RunRequest_ContinueInput struct {
	ContinueInput *ContinueInput `protobuf:"bytes,4,opt,name=continue_input,json=continueInput,proto3,oneof"`
}

func (*RunRequest_Prompt) isRunRequest_Input() {}

func (*RunRequest_ContinueInput) isRunRequest_Input() {}

type ContinueInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueInput) Reset() {
	*x = ContinueInput{}
	mi := &file_gotato_v2_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueInput) ProtoMessage() {}

func (x *ContinueInput) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueInput.ProtoReflect.Descriptor instead.
func (*ContinueInput) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{12}
}

type RunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	RunId         string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	FinalText     string                 `protobuf:"bytes,6,opt,name=final_text,json=finalText,proto3" json:"final_text,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
	Metrics       *RunMetrics            `protobuf:"bytes,8,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error         *RuntimeError          `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	Compacted     bool                   `protobuf:"varint,10,opt,name=compacted,proto3" json:"compacted,omitempty"`
	Messages      int32                  `protobuf:"varint,11,opt,name=messages,proto3" json:"messages,omitempty"`
	Events        int32                  `protobuf:"varint,12,opt,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResult) Reset() {
	*x = RunResult{}
	mi := &file_gotato_v2_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResult) ProtoMessage() {}

func (x *RunResult) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResult.ProtoReflect.Descriptor instead.
func (*RunResult) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{13}
}

func (x *RunResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunResult) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *RunResult) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunResult) GetFinalText() string {
	if x != nil {
		return x.FinalText
	}
	return ""
}

func (x *RunResult) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *RunResult) GetMetrics() *RunMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *RunResult) GetError() *RuntimeError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RunResult) GetCompacted() bool {
	if x != nil {
		return x.Compacted
	}
	return false
}

func (x *RunResult) GetMessages() int32 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *RunResult) GetEvents() int32 {
	if x != nil {
		return x.Events
	}
	return 0
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   uint64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  uint64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   uint64                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_gotato_v2_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{14}
}

func (x *Usage) GetInputTokens() uint64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() uint64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type RunMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ElapsedMs      int64                  `protobuf:"varint,1,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	Turns          uint32                 `protobuf:"varint,2,opt,name=turns,proto3" json:"turns,omitempty"`
	ToolCalls      uint32                 `protobuf:"varint,3,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	TextBytes      uint64                 `protobuf:"varint,4,opt,name=text_bytes,json=textBytes,proto3" json:"text_bytes,omitempty"`
	ReasoningBytes uint64                 `protobuf:"varint,5,opt,name=reasoning_bytes,json=reasoningBytes,proto3" json:"reasoning_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunMetrics) Reset() {
	*x = RunMetrics{}
	mi := &file_gotato_v2_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMetrics) ProtoMessage() {}

func (x *RunMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMetrics.ProtoReflect.Descriptor instead.
func (*RunMetrics) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{15}
}

func (x *RunMetrics) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *RunMetrics) GetTurns() uint32 {
	if x != nil {
		return x.Turns
	}
	return 0
}

func (x *RunMetrics) GetToolCalls() uint32 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *RunMetrics) GetTextBytes() uint64 {
	if x != nil {
		return x.TextBytes
	}
	return 0
}

func (x *RunMetrics) GetReasoningBytes() uint64 {
	if x != nil {
		return x.ReasoningBytes
	}
	return 0
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_gotato_v2_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{16}
}

func (x *RuntimeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RuntimeError) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RunUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*RunUpdate_Event
	//	*RunUpdate_Result
	Update        isRunUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunUpdate) Reset() {
	*x = RunUpdate{}
	mi := &file_gotato_v2_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunUpdate) ProtoMessage() {}

func (x *RunUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunUpdate.ProtoReflect.Descriptor instead.
func (*RunUpdate) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{17}
}

func (x *RunUpdate) GetUpdate() isRunUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *RunUpdate) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Update.(*RunUpdate_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *RunUpdate) GetResult() *RunResult {
	if x != nil {
		if x, ok := x.Update.(*RunUpdate_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isRunUpdate_Update interface {
	isRunUpdate_Update()
}

type RunUpdate_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type RunUpdate_Result struct {
	Result *RunResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*RunUpdate_Event) isRunUpdate_Update() {}

func (*RunUpdate_Result) isRunUpdate_Update() {}

// Event preserves runtime identity, class, correlation, and order. The
// payload travels as JSON with the keys documented in the root package.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	EventClass    string                 `protobuf:"bytes,5,opt,name=event_class,json=eventClass,proto3" json:"event_class,omitempty"`
	Turn          uint32                 `protobuf:"varint,6,opt,name=turn,proto3" json:"turn,omitempty"`
	MessageId     string                 `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,8,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,9,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Timestamp     string                 `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_gotato_v2_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{18}
}

func (x *Event) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetEventClass() string {
	if x != nil {
		return x.EventClass
	}
	return ""
}

func (x *Event) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *Event) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Event) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Event) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type CancelRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*CancelRunRequest_RunId
	//	*CancelRunRequest_SessionId
	Target        isCancelRunRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{19}
}

func (x *CancelRunRequest) GetTarget() isCancelRunRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		if x, ok := x.Target.(*CancelRunRequest_RunId); ok {
			return x.RunId
		}
	}
	return ""
}

func (x *CancelRunRequest) GetSessionId() string {
	if x != nil {
		if x, ok := x.Target.(*CancelRunRequest_SessionId); ok {
			return x.SessionId
		}
	}
	return ""
}

type isCancelRunRequest_Target interface {
	isCancelRunRequest_Target()
}

type CancelRunRequest_RunId struct {
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3,oneof"`
}

type CancelRunRequest_SessionId struct {
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3,oneof"`
}

func (*CancelRunRequest_RunId) isCancelRunRequest_Target() {}

func (*CancelRunRequest_SessionId) isCancelRunRequest_Target() {}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_gotato_v2_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{20}
}

type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{21}
}

func (x *EventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EventsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// ContextReport carries the modelctx.Report as JSON plus the fields a client
// needs without decoding it.
type ContextReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PrefixHash       string                 `protobuf:"bytes,2,opt,name=prefix_hash,json=prefixHash,proto3" json:"prefix_hash,omitempty"`
	ApproxTokens     int32                  `protobuf:"varint,3,opt,name=approx_tokens,json=approxTokens,proto3" json:"approx_tokens,omitempty"`
	SelectedMessages int32                  `protobuf:"varint,4,opt,name=selected_messages,json=selectedMessages,proto3" json:"selected_messages,omitempty"`
	ReportJson       []byte                 `protobuf:"bytes,5,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContextReport) Reset() {
	*x = ContextReport{}
	mi := &file_gotato_v2_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextReport) ProtoMessage() {}

func (x *ContextReport) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextReport.ProtoReflect.Descriptor instead.
func (*ContextReport) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{22}
}

func (x *ContextReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ContextReport) GetPrefixHash() string {
	if x != nil {
		return x.PrefixHash
	}
	return ""
}

func (x *ContextReport) GetApproxTokens() int32 {
	if x != nil {
		return x.ApproxTokens
	}
	return 0
}

func (x *ContextReport) GetSelectedMessages() int32 {
	if x != nil {
		return x.SelectedMessages
	}
	return 0
}

func (x *ContextReport) GetReportJson() []byte {
	if x != nil {
		return x.ReportJson
	}
	return nil
}

type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Keep          int32                  `protobuf:"varint,2,opt,name=keep,proto3" json:"keep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_gotato_v2_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{23}
}

func (x *CompactRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompactRequest) GetKeep() int32 {
	if x != nil {
		return x.Keep
	}
	return 0
}

type CompactResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Replaced       bool                   `protobuf:"varint,2,opt,name=replaced,proto3" json:"replaced,omitempty"`
	MessagesBefore int32                  `protobuf:"varint,3,opt,name=messages_before,json=messagesBefore,proto3" json:"messages_before,omitempty"`
	MessagesAfter  int32                  `protobuf:"varint,4,opt,name=messages_after,json=messagesAfter,proto3" json:"messages_after,omitempty"`
	TokensBefore   int32                  `protobuf:"varint,5,opt,name=tokens_before,json=tokensBefore,proto3" json:"tokens_before,omitempty"`
	TokensAfter    int32                  `protobuf:"varint,6,opt,name=tokens_after,json=tokensAfter,proto3" json:"tokens_after,omitempty"`
	CompactionJson []byte                 `protobuf:"bytes,7,opt,name=compaction_json,json=compactionJson,proto3" json:"compaction_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompactResult) Reset() {
	*x = CompactResult{}
	mi := &file_gotato_v2_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResult) ProtoMessage() {}

func (x *CompactResult) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v2_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResult.ProtoReflect.Descriptor instead.
func (*CompactResult) Descriptor() ([]byte, []int) {
	return file_gotato_v2_service_proto_rawDescGZIP(), []int{24}
}

func (x *CompactResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompactResult) GetReplaced() bool {
	if x != nil {
		return x.Replaced
	}
	return false
}

func (x *CompactResult) GetMessagesBefore() int32 {
	if x != nil {
		return x.MessagesBefore
	}
	return 0
}

func (x *CompactResult) GetMessagesAfter() int32 {
	if x != nil {
		return x.MessagesAfter
	}
	return 0
}

func (x *CompactResult) GetTokensBefore() int32 {
	if x != nil {
		return x.TokensBefore
	}
	return 0
}

func (x *CompactResult) GetTokensAfter() int32 {
	if x != nil {
		return x.TokensAfter
	}
	return 0
}

func (x *CompactResult) GetCompactionJson() []byte {
	if x != nil {
		return x.CompactionJson
	}
	return nil
}

var File_gotato_v2_service_proto protoreflect.FileDescriptor

const file_gotato_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x17gotato/v2/service.proto\x12\tgotato.v2\"\x11\n" +
	"\x0fContractRequest\",\n" +
	"\x10ContractResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x0f\n" +
	"\rAgentsRequest\"(\n" +
	"\x0eAgentsResponse\x12\x16\n" +
	"\x06agents\x18\x01 \x03(\tR\x06agents\"\xc4\x01\n" +
	"\x14CreateSessionRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.gotato.v2.CreateSessionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xd5\x02\n" +
	"\x0eSessionSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x1a\n" +
	"\bmessages\x18\x05 \x01(\x05R\bmessages\x12\x12\n" +
	"\x04runs\x18\x06 \x01(\x05R\x04runs\x12&\n" +
	"\x05usage\x18\a \x01(\v2\x10.gotato.v2.UsageR\x05usage\x12C\n" +
	"\bmetadata\x18\b \x03(\v2'.gotato.v2.SessionSummary.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x0fSessionDocument\x12#\n" +
	"\rdocument_json\x18\x01 \x01(\fR\fdocumentJson\"\x15\n" +
	"\x13ListSessionsRequest\"M\n" +
	"\x14ListSessionsResponse\x125\n" +
	"\bsessions\x18\x01 \x03(\v2\x19.gotato.v2.SessionSummaryR\bsessions\"1\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xa5\x02\n" +
	"\n" +
	"RunRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x18\n" +
	"\x06prompt\x18\x03 \x01(\tH\x00R\x06prompt\x12A\n" +
	"\x0econtinue_input\x18\x04 \x01(\v2\x18.gotato.v2.ContinueInputH\x00R\rcontinueInput\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.gotato.v2.RunRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05input\"\x0f\n" +
	"\rContinueInput\"\xfe\x02\n" +
	"\tRunResult\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"final_text\x18\x06 \x01(\tR\tfinalText\x12&\n" +
	"\x05usage\x18\a \x01(\v2\x10.gotato.v2.UsageR\x05usage\x12/\n" +
	"\ametrics\x18\b \x01(\v2\x15.gotato.v2.RunMetricsR\ametrics\x12-\n" +
	"\x05error\x18\t \x01(\v2\x17.gotato.v2.RuntimeErrorR\x05error\x12\x1c\n" +
	"\tcompacted\x18\n" +
	" \x01(\bR\tcompacted\x12\x1a\n" +
	"\bmessages\x18\v \x01(\x05R\bmessages\x12\x16\n" +
	"\x06events\x18\f \x01(\x05R\x06events\"r\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x04R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x04R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x04R\vtotalTokens\"\xa8\x01\n" +
	"\n" +
	"RunMetrics\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x01 \x01(\x03R\telapsedMs\x12\x14\n" +
	"\x05turns\x18\x02 \x01(\rR\x05turns\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\x03 \x01(\rR\ttoolCalls\x12\x1d\n" +
	"\n" +
	"text_bytes\x18\x04 \x01(\x04R\ttextBytes\x12'\n" +
	"\x0freasoning_bytes\x18\x05 \x01(\x04R\x0ereasoningBytes\"Z\n" +
	"\fRuntimeError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"o\n" +
	"\tRunUpdate\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x10.gotato.v2.EventH\x00R\x05event\x12.\n" +
	"\x06result\x18\x02 \x01(\v2\x14.gotato.v2.RunResultH\x00R\x06resultB\b\n" +
	"\x06update\"\xa0\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1f\n" +
	"\vevent_class\x18\x05 \x01(\tR\n" +
	"eventClass\x12\x12\n" +
	"\x04turn\x18\x06 \x01(\rR\x04turn\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\x12 \n" +
	"\ftool_call_id\x18\b \x01(\tR\n" +
	"toolCallId\x12!\n" +
	"\fpayload_json\x18\t \x01(\fR\vpayloadJson\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\tR\ttimestamp\"V\n" +
	"\x10CancelRunRequest\x12\x17\n" +
	"\x06run_id\x18\x01 \x01(\tH\x00R\x05runId\x12\x1f\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tH\x00R\tsessionIdB\b\n" +
	"\x06target\"\x13\n" +
	"\x11CancelRunResponse\"B\n" +
	"\rEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\xc2\x01\n" +
	"\rContextReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vprefix_hash\x18\x02 \x01(\tR\n" +
	"prefixHash\x12#\n" +
	"\rapprox_tokens\x18\x03 \x01(\x05R\fapproxTokens\x12+\n" +
	"\x11selected_messages\x18\x04 \x01(\x05R\x10selectedMessages\x12\x1f\n" +
	"\vreport_json\x18\x05 \x01(\fR\n" +
	"reportJson\"C\n" +
	"\x0eCompactRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04keep\x18\x02 \x01(\x05R\x04keep\"\x8b\x02\n" +
	"\rCompactResult\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\breplaced\x18\x02 \x01(\bR\breplaced\x12'\n" +
	"\x0fmessages_before\x18\x03 \x01(\x05R\x0emessagesBefore\x12%\n" +
	"\x0emessages_after\x18\x04 \x01(\x05R\rmessagesAfter\x12#\n" +
	"\rtokens_before\x18\x05 \x01(\x05R\ftokensBefore\x12!\n" +
	"\ftokens_after\x18\x06 \x01(\x05R\vtokensAfter\x12'\n" +
	"\x0fcompaction_json\x18\a \x01(\fR\x0ecompactionJson2\xfa\x06\n" +
	"\x0eSessionService\x12C\n" +
	"\bContract\x12\x1a.gotato.v2.ContractRequest\x1a\x1b.gotato.v2.ContractResponse\x12=\n" +
	"\x06Agents\x12\x18.gotato.v2.AgentsRequest\x1a\x19.gotato.v2.AgentsResponse\x12K\n" +
	"\rCreateSession\x12\x1f.gotato.v2.CreateSessionRequest\x1a\x19.gotato.v2.SessionSummary\x12C\n" +
	"\n" +
	"GetSession\x12\x19.gotato.v2.SessionRequest\x1a\x1a.gotato.v2.SessionDocument\x12O\n" +
	"\fListSessions\x12\x1e.gotato.v2.ListSessionsRequest\x1a\x1f.gotato.v2.ListSessionsResponse\x12L\n" +
	"\rDeleteSession\x12\x19.gotato.v2.SessionRequest\x1a .gotato.v2.DeleteSessionResponse\x12C\n" +
	"\vForkSession\x12\x19.gotato.v2.SessionRequest\x1a\x19.gotato.v2.SessionSummary\x122\n" +
	"\x03Run\x12\x15.gotato.v2.RunRequest\x1a\x14.gotato.v2.RunResult\x12:\n" +
	"\tStreamRun\x12\x15.gotato.v2.RunRequest\x1a\x14.gotato.v2.RunUpdate0\x01\x12F\n" +
	"\tCancelRun\x12\x1b.gotato.v2.CancelRunRequest\x1a\x1c.gotato.v2.CancelRunResponse\x126\n" +
	"\x06Events\x12\x18.gotato.v2.EventsRequest\x1a\x10.gotato.v2.Event0\x01\x12>\n" +
	"\aContext\x12\x19.gotato.v2.SessionRequest\x1a\x18.gotato.v2.ContextReport\x12>\n" +
	"\aCompact\x12\x19.gotato.v2.CompactRequest\x1a\x18.gotato.v2.CompactResultB?Z=github.com/jinhuang712/gotato/adapter/grpc/gotato/v2;gotatov2b\x06proto3"

var (
	file_gotato_v2_service_proto_rawDescOnce sync.Once
	file_gotato_v2_service_proto_rawDescData []byte
)

func file_gotato_v2_service_proto_rawDescGZIP() []byte {
	file_gotato_v2_service_proto_rawDescOnce.Do(func() {
		file_gotato_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gotato_v2_service_proto_rawDesc), len(file_gotato_v2_service_proto_rawDesc)))
	})
	return file_gotato_v2_service_proto_rawDescData
}

var file_gotato_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_gotato_v2_service_proto_goTypes = []any{
	(*ContractRequest)(nil),       // 0: gotato.v2.ContractRequest
	(*ContractResponse)(nil),      // 1: gotato.v2.ContractResponse
	(*AgentsRequest)(nil),         // 2: gotato.v2.AgentsRequest
	(*AgentsResponse)(nil),        // 3: gotato.v2.AgentsResponse
	(*CreateSessionRequest)(nil),  // 4: gotato.v2.CreateSessionRequest
	(*SessionRequest)(nil),        // 5: gotato.v2.SessionRequest
	(*SessionSummary)(nil),        // 6: gotato.v2.SessionSummary
	(*SessionDocument)(nil),       // 7: gotato.v2.SessionDocument
	(*ListSessionsRequest)(nil),   // 8: gotato.v2.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 9: gotato.v2.ListSessionsResponse
	(*DeleteSessionResponse)(nil), // 10: gotato.v2.DeleteSessionResponse
	(*RunRequest)(nil),            // 11: gotato.v2.RunRequest
	(*ContinueInput)(nil),         // 12: gotato.v2.ContinueInput
	(*RunResult)(nil),             // 13: gotato.v2.RunResult
	(*Usage)(nil),                 // 14: gotato.v2.Usage
	(*RunMetrics)(nil),            // 15: gotato.v2.RunMetrics
	(*RuntimeError)(nil),          // 16: gotato.v2.RuntimeError
	(*RunUpdate)(nil),             // 17: gotato.v2.RunUpdate
	(*Event)(nil),                 // 18: gotato.v2.Event
	(*CancelRunRequest)(nil),      // 19: gotato.v2.CancelRunRequest
	(*CancelRunResponse)(nil),     // 20: gotato.v2.CancelRunResponse
	(*EventsRequest)(nil),         // 21: gotato.v2.EventsRequest
	(*ContextReport)(nil),         // 22: gotato.v2.ContextReport
	(*CompactRequest)(nil),        // 23: gotato.v2.CompactRequest
	(*CompactResult)(nil),         // 24: gotato.v2.CompactResult
	nil,                           // 25: gotato.v2.CreateSessionRequest.MetadataEntry
	nil,                           // 26: gotato.v2.SessionSummary.MetadataEntry
	nil,                           // 27: gotato.v2.RunRequest.MetadataEntry
}
var file_gotato_v2_service_proto_depIdxs = []int32{
	25, // 0: gotato.v2.CreateSessionRequest.metadata:type_name -> gotato.v2.CreateSessionRequest.MetadataEntry
	14, // 1: gotato.v2.SessionSummary.usage:type_name -> gotato.v2.Usage
	26, // 2: gotato.v2.SessionSummary.metadata:type_name -> gotato.v2.SessionSummary.MetadataEntry
	6,  // 3: gotato.v2.ListSessionsResponse.sessions:type_name -> gotato.v2.SessionSummary
	12, // 4: gotato.v2.RunRequest.continue_input:type_name -> gotato.v2.ContinueInput
	27, // 5: gotato.v2.RunRequest.metadata:type_name -> gotato.v2.RunRequest.MetadataEntry
	14, // 6: gotato.v2.RunResult.usage:type_name -> gotato.v2.Usage
	15, // 7: gotato.v2.RunResult.metrics:type_name -> gotato.v2.RunMetrics
	16, // 8: gotato.v2.RunResult.error:type_name -> gotato.v2.RuntimeError
	18, // 9: gotato.v2.RunUpdate.event:type_name -> gotato.v2.Event
	13, // 10: gotato.v2.RunUpdate.result:type_name -> gotato.v2.RunResult
	0,  // 11: gotato.v2.SessionService.Contract:input_type -> gotato.v2.ContractRequest
	2,  // 12: gotato.v2.SessionService.Agents:input_type -> gotato.v2.AgentsRequest
	4,  // 13: gotato.v2.SessionService.CreateSession:input_type -> gotato.v2.CreateSessionRequest
	5,  // 14: gotato.v2.SessionService.GetSession:input_type -> gotato.v2.SessionRequest
	8,  // 15: gotato.v2.SessionService.ListSessions:input_type -> gotato.v2.ListSessionsRequest
	5,  // 16: gotato.v2.SessionService.DeleteSession:input_type -> gotato.v2.SessionRequest
	5,  // 17: gotato.v2.SessionService.ForkSession:input_type -> gotato.v2.SessionRequest
	11, // 18: gotato.v2.SessionService.Run:input_type -> gotato.v2.RunRequest
	11, // 19: gotato.v2.SessionService.StreamRun:input_type -> gotato.v2.RunRequest
	19, // 20: gotato.v2.SessionService.CancelRun:input_type -> gotato.v2.CancelRunRequest
	21, // 21: gotato.v2.SessionService.Events:input_type -> gotato.v2.EventsRequest
	5,  // 22: gotato.v2.SessionService.Context:input_type -> gotato.v2.SessionRequest
	23, // 23: gotato.v2.SessionService.Compact:input_type -> gotato.v2.CompactRequest
	1,  // 24: gotato.v2.SessionService.Contract:output_type -> gotato.v2.ContractResponse
	3,  // 25: gotato.v2.SessionService.Agents:output_type -> gotato.v2.AgentsResponse
	6,  // 26: gotato.v2.SessionService.CreateSession:output_type -> gotato.v2.SessionSummary
	7,  // 27: gotato.v2.SessionService.GetSession:output_type -> gotato.v2.SessionDocument
	9,  // 28: gotato.v2.SessionService.ListSessions:output_type -> gotato.v2.ListSessionsResponse
	10, // 29: gotato.v2.SessionService.DeleteSession:output_type -> gotato.v2.DeleteSessionResponse
	6,  // 30: gotato.v2.SessionService.ForkSession:output_type -> gotato.v2.SessionSummary
	13, // 31: gotato.v2.SessionService.Run:output_type -> gotato.v2.RunResult
	17, // 32: gotato.v2.SessionService.StreamRun:output_type -> gotato.v2.RunUpdate
	20, // 33: gotato.v2.SessionService.CancelRun:output_type -> gotato.v2.CancelRunResponse
	18, // 34: gotato.v2.SessionService.Events:output_type -> gotato.v2.Event
	22, // 35: gotato.v2.SessionService.Context:output_type -> gotato.v2.ContextReport
	24, // 36: gotato.v2.SessionService.Compact:output_type -> gotato.v2.CompactResult
	24, // [24:37] is the sub-list for method output_type
	11, // [11:24] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gotato_v2_service_proto_init() }
func file_gotato_v2_service_proto_init() {
	if File_gotato_v2_service_proto != nil {
		return
	}
	file_gotato_v2_service_proto_msgTypes[11].OneofWrappers = []any{
		(*RunRequest_Prompt)(nil),
		(*RunRequest_ContinueInput)(nil),
	}
	file_gotato_v2_service_proto_msgTypes[17].OneofWrappers = []any{
		(*RunUpdate_Event)(nil),
		(*RunUpdate_Result)(nil),
	}
	file_gotato_v2_service_proto_msgTypes[19].OneofWrappers = []any{
		(*CancelRunRequest_RunId)(nil),
		(*CancelRunRequest_SessionId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gotato_v2_service_proto_rawDesc), len(file_gotato_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gotato_v2_service_proto_goTypes,
		DependencyIndexes: file_gotato_v2_service_proto_depIdxs,
		MessageInfos:      file_gotato_v2_service_proto_msgTypes,
	}.Build()
	File_gotato_v2_service_proto = out.File
	file_gotato_v2_service_proto_goTypes = nil
	file_gotato_v2_service_proto_depIdxs = nil
}
