// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: gotato/v1/agent.proto

package gotatov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Contract_FullMethodName        = "/gotato.v1.AgentService/Contract"
	AgentService_Run_FullMethodName             = "/gotato.v1.AgentService/Run"
	AgentService_StreamRun_FullMethodName       = "/gotato.v1.AgentService/StreamRun"
	AgentService_CancelRun_FullMethodName       = "/gotato.v1.AgentService/CancelRun"
	AgentService_GetConversation_FullMethodName = "/gotato.v1.AgentService/GetConversation"
	AgentService_CloseAgent_FullMethodName      = "/gotato.v1.AgentService/CloseAgent"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is one protocol adapter over the Host semantic boundary. It
// defines no Agent semantics of its own: every RPC maps onto host.Service.
type AgentServiceClient interface {
	// Contract reports the frozen Host contract version behind this adapter.
	Contract(ctx context.Context, in *ContractRequest, opts ...grpc.CallOption) (*ContractResponse, error)
	// Run settles one command and returns its outcome.
	Run(ctx context.Context, in *RunCommand, opts ...grpc.CallOption) (*RunOutcome, error)
	// StreamRun settles one command while streaming its canonical Events. The
	// terminal outcome is the last message on the stream.
	StreamRun(ctx context.Context, in *RunCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunUpdate], error)
	// CancelRun aborts an active Run. It is idempotent while the Run is active
	// and reports not-active afterwards rather than pretending to cancel.
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error)
	// GetConversation reports one routing record. It carries no transcript.
	GetConversation(ctx context.Context, in *ConversationRequest, opts ...grpc.CallOption) (*ConversationRecord, error)
	// CloseAgent closes one live Core Agent.
	CloseAgent(ctx context.Context, in *CloseAgentRequest, opts ...grpc.CallOption) (*CloseAgentResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Contract(ctx context.Context, in *ContractRequest, opts ...grpc.CallOption) (*ContractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractResponse)
	err := c.cc.Invoke(ctx, AgentService_Contract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Run(ctx context.Context, in *RunCommand, opts ...grpc.CallOption) (*RunOutcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunOutcome)
	err := c.cc.Invoke(ctx, AgentService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamRun(ctx context.Context, in *RunCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunCommand, RunUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamRunClient = grpc.ServerStreamingClient[RunUpdate]

func (c *agentServiceClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRunResponse)
	err := c.cc.Invoke(ctx, AgentService_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetConversation(ctx context.Context, in *ConversationRequest, opts ...grpc.CallOption) (*ConversationRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationRecord)
	err := c.cc.Invoke(ctx, AgentService_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CloseAgent(ctx context.Context, in *CloseAgentRequest, opts ...grpc.CallOption) (*CloseAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_CloseAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is one protocol adapter over the Host semantic boundary. It
// defines no Agent semantics of its own: every RPC maps onto host.Service.
type AgentServiceServer interface {
	// Contract reports the frozen Host contract version behind this adapter.
	Contract(context.Context, *ContractRequest) (*ContractResponse, error)
	// Run settles one command and returns its outcome.
	Run(context.Context, *RunCommand) (*RunOutcome, error)
	// StreamRun settles one command while streaming its canonical Events. The
	// terminal outcome is the last message on the stream.
	StreamRun(*RunCommand, grpc.ServerStreamingServer[RunUpdate]) error
	// CancelRun aborts an active Run. It is idempotent while the Run is active
	// and reports not-active afterwards rather than pretending to cancel.
	CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error)
	// GetConversation reports one routing record. It carries no transcript.
	GetConversation(context.Context, *ConversationRequest) (*ConversationRecord, error)
	// CloseAgent closes one live Core Agent.
	CloseAgent(context.Context, *CloseAgentRequest) (*CloseAgentResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Contract(context.Context, *ContractRequest) (*ContractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Contract not implemented")
}
func (UnimplementedAgentServiceServer) Run(context.Context, *RunCommand) (*RunOutcome, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAgentServiceServer) StreamRun(*RunCommand, grpc.ServerStreamingServer[RunUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamRun not implemented")
}
func (UnimplementedAgentServiceServer) CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedAgentServiceServer) GetConversation(context.Context, *ConversationRequest) (*ConversationRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedAgentServiceServer) CloseAgent(context.Context, *CloseAgentRequest) (*CloseAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseAgent not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Contract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Contract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Contract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Contract(ctx, req.(*ContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Run(ctx, req.(*RunCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamRun(m, &grpc.GenericServerStream[RunCommand, RunUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamRunServer = grpc.ServerStreamingServer[RunUpdate]

func _AgentService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetConversation(ctx, req.(*ConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CloseAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CloseAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CloseAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CloseAgent(ctx, req.(*CloseAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotato.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Contract",
			Handler:    _AgentService_Contract_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _AgentService_Run_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _AgentService_CancelRun_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _AgentService_GetConversation_Handler,
		},
		{
			MethodName: "CloseAgent",
			Handler:    _AgentService_CloseAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRun",
			Handler:       _AgentService_StreamRun_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gotato/v1/agent.proto",
}
