// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gotato/v1/agent.proto

package gotatov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractRequest) Reset() {
	*x = ContractRequest{}
	mi := &file_gotato_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRequest) ProtoMessage() {}

func (x *ContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRequest.ProtoReflect.Descriptor instead.
func (*ContractRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{0}
}

type ContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractResponse) Reset() {
	*x = ContractResponse{}
	mi := &file_gotato_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractResponse) ProtoMessage() {}

func (x *ContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractResponse.ProtoReflect.Descriptor instead.
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ContractResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// RunCommand carries exactly one input: either a prompt or a continue.
type RunCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentName string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	// Types that are valid to be assigned to Conversation:
	//
	//	*RunCommand_ConversationId
	//	*RunCommand_ConversationKey
	Conversation isRunCommand_Conversation `protobuf_oneof:"conversation"`
	// Types that are valid to be assigned to Input:
	//
	//	*RunCommand_Prompt
	//	*RunCommand_ContinueInput
	Input              isRunCommand_Input `protobuf_oneof:"input"`
	ExpectedGeneration *uint64            `protobuf:"varint,6,opt,name=expected_generation,json=expectedGeneration,proto3,oneof" json:"expected_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunCommand) Reset() {
	*x = RunCommand{}
	mi := &file_gotato_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommand) ProtoMessage() {}

func (x *RunCommand) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommand.ProtoReflect.Descriptor instead.
func (*RunCommand) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RunCommand) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RunCommand) GetConversation() isRunCommand_Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *RunCommand) GetConversationId() string {
	if x != nil {
		if x, ok := x.Conversation.(*RunCommand_ConversationId); ok {
			return x.ConversationId
		}
	}
	return ""
}

func (x *RunCommand) GetConversationKey() string {
	if x != nil {
		if x, ok := x.Conversation.(*RunCommand_ConversationKey); ok {
			return x.ConversationKey
		}
	}
	return ""
}

func (x *RunCommand) GetInput() isRunCommand_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunCommand) GetPrompt() string {
	if x != nil {
		if x, ok := x.Input.(*RunCommand_Prompt); ok {
			return x.Prompt
		}
	}
	return ""
}

func (x *RunCommand) GetContinueInput() *ContinueInput {
	if x != nil {
		if x, ok := x.Input.(*RunCommand_ContinueInput); ok {
			return x.ContinueInput
		}
	}
	return nil
}

func (x *RunCommand) GetExpectedGeneration() uint64 {
	if x != nil && x.ExpectedGeneration != nil {
		return *x.ExpectedGeneration
	}
	return 0
}

type isRunCommand_Conversation interface {
	isRunCommand_Conversation()
}

type RunCommand_ConversationId struct {
	ConversationId string `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3,oneof"`
}

type RunCommand_ConversationKey struct {
	ConversationKey string `protobuf:"bytes,3,opt,name=conversation_key,json=conversationKey,proto3,oneof"`
}

func (*RunCommand_ConversationId) isRunCommand_Conversation() {}

func (*RunCommand_ConversationKey) isRunCommand_Conversation() {}

type isRunCommand_Input interface {
	isRunCommand_Input()
}

type RunCommand_Prompt struct {
	Prompt string `protobuf:"bytes,4,opt,name=prompt,proto3,oneof"`
}

type RunCommand_ContinueInput struct {
	ContinueInput *ContinueInput `protobuf:"bytes,5,opt,name=continue_input,json=continueInput,proto3,oneof"`
}

func (*RunCommand_Prompt) isRunCommand_Input() {}

func (*RunCommand_ContinueInput) isRunCommand_Input() {}

type ContinueInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueInput) Reset() {
	*x = ContinueInput{}
	mi := &file_gotato_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueInput) ProtoMessage() {}

func (x *ContinueInput) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueInput.ProtoReflect.Descriptor instead.
func (*ContinueInput) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{3}
}

type RunOutcome struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentGeneration uint64                 `protobuf:"varint,3,opt,name=agent_generation,json=agentGeneration,proto3" json:"agent_generation,omitempty"`
	RunId           string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	FinalMessage    string                 `protobuf:"bytes,6,opt,name=final_message,json=finalMessage,proto3" json:"final_message,omitempty"`
	Usage           *Usage                 `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
	Metrics         *RunMetrics            `protobuf:"bytes,8,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error           *RuntimeError          `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunOutcome) Reset() {
	*x = RunOutcome{}
	mi := &file_gotato_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOutcome) ProtoMessage() {}

func (x *RunOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOutcome.ProtoReflect.Descriptor instead.
func (*RunOutcome) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RunOutcome) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RunOutcome) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunOutcome) GetAgentGeneration() uint64 {
	if x != nil {
		return x.AgentGeneration
	}
	return 0
}

func (x *RunOutcome) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunOutcome) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunOutcome) GetFinalMessage() string {
	if x != nil {
		return x.FinalMessage
	}
	return ""
}

func (x *RunOutcome) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *RunOutcome) GetMetrics() *RunMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *RunOutcome) GetError() *RuntimeError {
	if x != nil {
		return x.Error
	}
	return nil
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   uint64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  uint64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   uint64                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_gotato_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Usage) GetInputTokens() uint64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() uint64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type RunMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ElapsedMs      int64                  `protobuf:"varint,1,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	Turns          uint32                 `protobuf:"varint,2,opt,name=turns,proto3" json:"turns,omitempty"`
	ToolCalls      uint32                 `protobuf:"varint,3,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	TextBytes      uint64                 `protobuf:"varint,4,opt,name=text_bytes,json=textBytes,proto3" json:"text_bytes,omitempty"`
	ReasoningBytes uint64                 `protobuf:"varint,5,opt,name=reasoning_bytes,json=reasoningBytes,proto3" json:"reasoning_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunMetrics) Reset() {
	*x = RunMetrics{}
	mi := &file_gotato_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMetrics) ProtoMessage() {}

func (x *RunMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMetrics.ProtoReflect.Descriptor instead.
func (*RunMetrics) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RunMetrics) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *RunMetrics) GetTurns() uint32 {
	if x != nil {
		return x.Turns
	}
	return 0
}

func (x *RunMetrics) GetToolCalls() uint32 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *RunMetrics) GetTextBytes() uint64 {
	if x != nil {
		return x.TextBytes
	}
	return 0
}

func (x *RunMetrics) GetReasoningBytes() uint64 {
	if x != nil {
		return x.ReasoningBytes
	}
	return 0
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_gotato_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RuntimeError) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RunUpdate is either one projected Event or the terminal outcome.
type RunUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*RunUpdate_Event
	//	*RunUpdate_Outcome
	Update        isRunUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunUpdate) Reset() {
	*x = RunUpdate{}
	mi := &file_gotato_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunUpdate) ProtoMessage() {}

func (x *RunUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunUpdate.ProtoReflect.Descriptor instead.
func (*RunUpdate) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RunUpdate) GetUpdate() isRunUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *RunUpdate) GetEvent() *RunEvent {
	if x != nil {
		if x, ok := x.Update.(*RunUpdate_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *RunUpdate) GetOutcome() *RunOutcome {
	if x != nil {
		if x, ok := x.Update.(*RunUpdate_Outcome); ok {
			return x.Outcome
		}
	}
	return nil
}

type isRunUpdate_Update interface {
	isRunUpdate_Update()
}

type RunUpdate_Event struct {
	Event *RunEvent `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type RunUpdate_Outcome struct {
	Outcome *RunOutcome `protobuf:"bytes,2,opt,name=outcome,proto3,oneof"`
}

func (*RunUpdate_Event) isRunUpdate_Update() {}

func (*RunUpdate_Outcome) isRunUpdate_Update() {}

// RunEvent preserves Core identity, class, correlation, and order. The payload
// travels as JSON so the adapter never has to redefine what an Event means.
type RunEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RunId       string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Sequence    uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Kind        string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	EventClass  string                 `protobuf:"bytes,5,opt,name=event_class,json=eventClass,proto3" json:"event_class,omitempty"`
	Turn        uint32                 `protobuf:"varint,6,opt,name=turn,proto3" json:"turn,omitempty"`
	MessageId   string                 `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ToolCallId  string                 `protobuf:"bytes,8,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	SpawnId     string                 `protobuf:"bytes,9,opt,name=spawn_id,json=spawnId,proto3" json:"spawn_id,omitempty"`
	OriginRunId string                 `protobuf:"bytes,10,opt,name=origin_run_id,json=originRunId,proto3" json:"origin_run_id,omitempty"`
	PayloadJson []byte                 `protobuf:"bytes,11,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	// Routing metadata Orchestration adds. It does not change Core meaning.
	ConversationId  string `protobuf:"bytes,12,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AgentGeneration uint64 `protobuf:"varint,13,opt,name=agent_generation,json=agentGeneration,proto3" json:"agent_generation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_gotato_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RunEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RunEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RunEvent) GetEventClass() string {
	if x != nil {
		return x.EventClass
	}
	return ""
}

func (x *RunEvent) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *RunEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RunEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *RunEvent) GetSpawnId() string {
	if x != nil {
		return x.SpawnId
	}
	return ""
}

func (x *RunEvent) GetOriginRunId() string {
	if x != nil {
		return x.OriginRunId
	}
	return ""
}

func (x *RunEvent) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *RunEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RunEvent) GetAgentGeneration() uint64 {
	if x != nil {
		return x.AgentGeneration
	}
	return 0
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_gotato_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_gotato_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{11}
}

type ConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationRequest) Reset() {
	*x = ConversationRequest{}
	mi := &file_gotato_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationRequest) ProtoMessage() {}

func (x *ConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationRequest.ProtoReflect.Descriptor instead.
func (*ConversationRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type ConversationRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationKey string                 `protobuf:"bytes,2,opt,name=conversation_key,json=conversationKey,proto3" json:"conversation_key,omitempty"`
	AgentName       string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	LiveAgentId     string                 `protobuf:"bytes,4,opt,name=live_agent_id,json=liveAgentId,proto3" json:"live_agent_id,omitempty"`
	AgentGeneration uint64                 `protobuf:"varint,5,opt,name=agent_generation,json=agentGeneration,proto3" json:"agent_generation,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConversationRecord) Reset() {
	*x = ConversationRecord{}
	mi := &file_gotato_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationRecord) ProtoMessage() {}

func (x *ConversationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationRecord.ProtoReflect.Descriptor instead.
func (*ConversationRecord) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ConversationRecord) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationRecord) GetConversationKey() string {
	if x != nil {
		return x.ConversationKey
	}
	return ""
}

func (x *ConversationRecord) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *ConversationRecord) GetLiveAgentId() string {
	if x != nil {
		return x.LiveAgentId
	}
	return ""
}

func (x *ConversationRecord) GetAgentGeneration() uint64 {
	if x != nil {
		return x.AgentGeneration
	}
	return 0
}

func (x *ConversationRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CloseAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAgentRequest) Reset() {
	*x = CloseAgentRequest{}
	mi := &file_gotato_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAgentRequest) ProtoMessage() {}

func (x *CloseAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAgentRequest.ProtoReflect.Descriptor instead.
func (*CloseAgentRequest) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CloseAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type CloseAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAgentResponse) Reset() {
	*x = CloseAgentResponse{}
	mi := &file_gotato_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAgentResponse) ProtoMessage() {}

func (x *CloseAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gotato_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAgentResponse.ProtoReflect.Descriptor instead.
func (*CloseAgentResponse) Descriptor() ([]byte, []int) {
	return file_gotato_v1_agent_proto_rawDescGZIP(), []int{15}
}

var File_gotato_v1_agent_proto protoreflect.FileDescriptor

const file_gotato_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x15gotato/v1/agent.proto\x12\tgotato.v1\"\x11\n" +
	"\x0fContractRequest\",\n" +
	"\x10ContractResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xc7\x02\n" +
	"\n" +
	"RunCommand\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12)\n" +
	"\x0fconversation_id\x18\x02 \x01(\tH\x00R\x0econversationId\x12+\n" +
	"\x10conversation_key\x18\x03 \x01(\tH\x00R\x0fconversationKey\x12\x18\n" +
	"\x06prompt\x18\x04 \x01(\tH\x01R\x06prompt\x12A\n" +
	"\x0econtinue_input\x18\x05 \x01(\v2\x18.gotato.v1.ContinueInputH\x01R\rcontinueInput\x124\n" +
	"\x13expected_generation\x18\x06 \x01(\x04H\x02R\x12expectedGeneration\x88\x01\x01B\x0e\n" +
	"\fconversationB\a\n" +
	"\x05inputB\x16\n" +
	"\x14_expected_generation\"\x0f\n" +
	"\rContinueInput\"\xd7\x02\n" +
	"\n" +
	"RunOutcome\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12)\n" +
	"\x10agent_generation\x18\x03 \x01(\x04R\x0fagentGeneration\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rfinal_message\x18\x06 \x01(\tR\ffinalMessage\x12&\n" +
	"\x05usage\x18\a \x01(\v2\x10.gotato.v1.UsageR\x05usage\x12/\n" +
	"\ametrics\x18\b \x01(\v2\x15.gotato.v1.RunMetricsR\ametrics\x12-\n" +
	"\x05error\x18\t \x01(\v2\x17.gotato.v1.RuntimeErrorR\x05error\"r\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x04R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x04R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x04R\vtotalTokens\"\xa8\x01\n" +
	"\n" +
	"RunMetrics\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x01 \x01(\x03R\telapsedMs\x12\x14\n" +
	"\x05turns\x18\x02 \x01(\rR\x05turns\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\x03 \x01(\rR\ttoolCalls\x12\x1d\n" +
	"\n" +
	"text_bytes\x18\x04 \x01(\x04R\ttextBytes\x12'\n" +
	"\x0freasoning_bytes\x18\x05 \x01(\x04R\x0ereasoningBytes\"Z\n" +
	"\fRuntimeError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"u\n" +
	"\tRunUpdate\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x13.gotato.v1.RunEventH\x00R\x05event\x121\n" +
	"\aoutcome\x18\x02 \x01(\v2\x15.gotato.v1.RunOutcomeH\x00R\aoutcomeB\b\n" +
	"\x06update\"\x98\x03\n" +
	"\bRunEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1f\n" +
	"\vevent_class\x18\x05 \x01(\tR\n" +
	"eventClass\x12\x12\n" +
	"\x04turn\x18\x06 \x01(\rR\x04turn\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\x12 \n" +
	"\ftool_call_id\x18\b \x01(\tR\n" +
	"toolCallId\x12\x19\n" +
	"\bspawn_id\x18\t \x01(\tR\aspawnId\x12\"\n" +
	"\rorigin_run_id\x18\n" +
	" \x01(\tR\voriginRunId\x12!\n" +
	"\fpayload_json\x18\v \x01(\fR\vpayloadJson\x12'\n" +
	"\x0fconversation_id\x18\f \x01(\tR\x0econversationId\x12)\n" +
	"\x10agent_generation\x18\r \x01(\x04R\x0fagentGeneration\")\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x13\n" +
	"\x11CancelRunResponse\">\n" +
	"\x13ConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\xee\x01\n" +
	"\x12ConversationRecord\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12)\n" +
	"\x10conversation_key\x18\x02 \x01(\tR\x0fconversationKey\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\x12\"\n" +
	"\rlive_agent_id\x18\x04 \x01(\tR\vliveAgentId\x12)\n" +
	"\x10agent_generation\x18\x05 \x01(\x04R\x0fagentGeneration\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\".\n" +
	"\x11CloseAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x14\n" +
	"\x12CloseAgentResponse2\xa9\x03\n" +
	"\fAgentService\x12C\n" +
	"\bContract\x12\x1a.gotato.v1.ContractRequest\x1a\x1b.gotato.v1.ContractResponse\x123\n" +
	"\x03Run\x12\x15.gotato.v1.RunCommand\x1a\x15.gotato.v1.RunOutcome\x12:\n" +
	"\tStreamRun\x12\x15.gotato.v1.RunCommand\x1a\x14.gotato.v1.RunUpdate0\x01\x12F\n" +
	"\tCancelRun\x12\x1b.gotato.v1.CancelRunRequest\x1a\x1c.gotato.v1.CancelRunResponse\x12P\n" +
	"\x0fGetConversation\x12\x1e.gotato.v1.ConversationRequest\x1a\x1d.gotato.v1.ConversationRecord\x12I\n" +
	"\n" +
	"CloseAgent\x12\x1c.gotato.v1.CloseAgentRequest\x1a\x1d.gotato.v1.CloseAgentResponseB?Z=github.com/jinhuang712/gotato/adapter/grpc/gotato/v1;gotatov1b\x06proto3"

var (
	file_gotato_v1_agent_proto_rawDescOnce sync.Once
	file_gotato_v1_agent_proto_rawDescData []byte
)

func file_gotato_v1_agent_proto_rawDescGZIP() []byte {
	file_gotato_v1_agent_proto_rawDescOnce.Do(func() {
		file_gotato_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gotato_v1_agent_proto_rawDesc), len(file_gotato_v1_agent_proto_rawDesc)))
	})
	return file_gotato_v1_agent_proto_rawDescData
}

var file_gotato_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gotato_v1_agent_proto_goTypes = []any{
	(*ContractRequest)(nil),     // 0: gotato.v1.ContractRequest
	(*ContractResponse)(nil),    // 1: gotato.v1.ContractResponse
	(*RunCommand)(nil),          // 2: gotato.v1.RunCommand
	(*ContinueInput)(nil),       // 3: gotato.v1.ContinueInput
	(*RunOutcome)(nil),          // 4: gotato.v1.RunOutcome
	(*Usage)(nil),               // 5: gotato.v1.Usage
	(*RunMetrics)(nil),          // 6: gotato.v1.RunMetrics
	(*RuntimeError)(nil),        // 7: gotato.v1.RuntimeError
	(*RunUpdate)(nil),           // 8: gotato.v1.RunUpdate
	(*RunEvent)(nil),            // 9: gotato.v1.RunEvent
	(*CancelRunRequest)(nil),    // 10: gotato.v1.CancelRunRequest
	(*CancelRunResponse)(nil),   // 11: gotato.v1.CancelRunResponse
	(*ConversationRequest)(nil), // 12: gotato.v1.ConversationRequest
	(*ConversationRecord)(nil),  // 13: gotato.v1.ConversationRecord
	(*CloseAgentRequest)(nil),   // 14: gotato.v1.CloseAgentRequest
	(*CloseAgentResponse)(nil),  // 15: gotato.v1.CloseAgentResponse
}
var file_gotato_v1_agent_proto_depIdxs = []int32{
	3,  // 0: gotato.v1.RunCommand.continue_input:type_name -> gotato.v1.ContinueInput
	5,  // 1: gotato.v1.RunOutcome.usage:type_name -> gotato.v1.Usage
	6,  // 2: gotato.v1.RunOutcome.metrics:type_name -> gotato.v1.RunMetrics
	7,  // 3: gotato.v1.RunOutcome.error:type_name -> gotato.v1.RuntimeError
	9,  // 4: gotato.v1.RunUpdate.event:type_name -> gotato.v1.RunEvent
	4,  // 5: gotato.v1.RunUpdate.outcome:type_name -> gotato.v1.RunOutcome
	0,  // 6: gotato.v1.AgentService.Contract:input_type -> gotato.v1.ContractRequest
	2,  // 7: gotato.v1.AgentService.Run:input_type -> gotato.v1.RunCommand
	2,  // 8: gotato.v1.AgentService.StreamRun:input_type -> gotato.v1.RunCommand
	10, // 9: gotato.v1.AgentService.CancelRun:input_type -> gotato.v1.CancelRunRequest
	12, // 10: gotato.v1.AgentService.GetConversation:input_type -> gotato.v1.ConversationRequest
	14, // 11: gotato.v1.AgentService.CloseAgent:input_type -> gotato.v1.CloseAgentRequest
	1,  // 12: gotato.v1.AgentService.Contract:output_type -> gotato.v1.ContractResponse
	4,  // 13: gotato.v1.AgentService.Run:output_type -> gotato.v1.RunOutcome
	8,  // 14: gotato.v1.AgentService.StreamRun:output_type -> gotato.v1.RunUpdate
	11, // 15: gotato.v1.AgentService.CancelRun:output_type -> gotato.v1.CancelRunResponse
	13, // 16: gotato.v1.AgentService.GetConversation:output_type -> gotato.v1.ConversationRecord
	15, // 17: gotato.v1.AgentService.CloseAgent:output_type -> gotato.v1.CloseAgentResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_gotato_v1_agent_proto_init() }
func file_gotato_v1_agent_proto_init() {
	if File_gotato_v1_agent_proto != nil {
		return
	}
	file_gotato_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*RunCommand_ConversationId)(nil),
		(*RunCommand_ConversationKey)(nil),
		(*RunCommand_Prompt)(nil),
		(*RunCommand_ContinueInput)(nil),
	}
	file_gotato_v1_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*RunUpdate_Event)(nil),
		(*RunUpdate_Outcome)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gotato_v1_agent_proto_rawDesc), len(file_gotato_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gotato_v1_agent_proto_goTypes,
		DependencyIndexes: file_gotato_v1_agent_proto_depIdxs,
		MessageInfos:      file_gotato_v1_agent_proto_msgTypes,
	}.Build()
	File_gotato_v1_agent_proto = out.File
	file_gotato_v1_agent_proto_goTypes = nil
	file_gotato_v1_agent_proto_depIdxs = nil
}
