package orchestration

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	gotato "github.com/jinhuang712/gotato"
)

// FileSnapshotStore keeps retained Conversation state on disk, one file per
// Conversation. It is the reference durable store: it needs no database,
// broker, or service, which keeps the "runs in an existing Go process"
// promise intact while still surviving a restart.
//
// A deployment that wants a real database implements SnapshotStore itself;
// nothing above this type knows which one it got.
type FileSnapshotStore struct {
	mu  sync.Mutex
	dir string
	// maxBytes bounds one serialized state. A Conversation that outgrows it
	// fails its retirement loudly instead of writing a file nothing can load.
	maxBytes int
}

// DefaultSnapshotBytes bounds one serialized Conversation state.
const DefaultSnapshotBytes = 8 << 20

// NewFileSnapshotStore opens or creates a store rooted at dir.
func NewFileSnapshotStore(dir string) (*FileSnapshotStore, error) {
	if strings.TrimSpace(dir) == "" {
		return nil, gotatoError(gotato.ErrInvalidArgument, "snapshot directory is empty")
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, gotatoError(gotato.ErrInvalidArgument, "cannot open snapshot directory: "+err.Error())
	}
	return &FileSnapshotStore{dir: dir, maxBytes: DefaultSnapshotBytes}, nil
}

// SetMaxBytes bounds one serialized state.
func (s *FileSnapshotStore) SetMaxBytes(limit int) {
	s.mu.Lock()
	s.maxBytes = limit
	s.mu.Unlock()
}

// fileName maps a Conversation ID onto a file name. IDs are generated by this
// package and contain no path separators, but the check stays because a
// durable store must never be talked into writing outside its directory.
func (s *FileSnapshotStore) fileName(id gotato.ConversationID) (string, error) {
	name := string(id)
	if name == "" || strings.ContainsAny(name, `/\`) || name == "." || name == ".." {
		return "", gotatoError(gotato.ErrInvalidArgument, "unusable Conversation ID for a file store: "+name)
	}
	return filepath.Join(s.dir, name+".json"), nil
}

func (s *FileSnapshotStore) Save(ctx context.Context, state StoredState) error {
	if err := contextError(ctx); err != nil {
		return err
	}
	path, err := s.fileName(state.Record.ID)
	if err != nil {
		return err
	}
	encoded, err := json.Marshal(state)
	if err != nil {
		return gotatoError(gotato.ErrInvalidState, "cannot encode Conversation state: "+err.Error())
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	if s.maxBytes > 0 && len(encoded) > s.maxBytes {
		return gotatoError(gotato.ErrLimitExceeded, "Conversation state exceeds the snapshot size bound")
	}
	if existing, ok, readErr := s.readLocked(path); readErr != nil {
		return readErr
	} else if ok && state.Record.StateVersion <= existing.Record.StateVersion {
		return staleStateError(state.Record.ID)
	}

	// Write to a temporary file and rename, so a reader never sees a half
	// written state and a crash mid-write leaves the previous one intact.
	temporary, err := os.CreateTemp(s.dir, "state-*.tmp")
	if err != nil {
		return gotatoError(gotato.ErrInvalidState, "cannot stage Conversation state: "+err.Error())
	}
	name := temporary.Name()
	if _, err := temporary.Write(encoded); err != nil {
		temporary.Close()
		os.Remove(name)
		return gotatoError(gotato.ErrInvalidState, "cannot write Conversation state: "+err.Error())
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		os.Remove(name)
		return gotatoError(gotato.ErrInvalidState, "cannot flush Conversation state: "+err.Error())
	}
	if err := temporary.Close(); err != nil {
		os.Remove(name)
		return gotatoError(gotato.ErrInvalidState, "cannot close Conversation state: "+err.Error())
	}
	if err := os.Rename(name, path); err != nil {
		os.Remove(name)
		return gotatoError(gotato.ErrInvalidState, "cannot commit Conversation state: "+err.Error())
	}
	return nil
}

func (s *FileSnapshotStore) readLocked(path string) (StoredState, bool, error) {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return StoredState{}, false, nil
	}
	if err != nil {
		return StoredState{}, false, gotatoError(gotato.ErrInvalidState, "cannot read Conversation state: "+err.Error())
	}
	var state StoredState
	if err := json.Unmarshal(raw, &state); err != nil {
		return StoredState{}, false, gotatoError(gotato.ErrInvalidState, "cannot decode Conversation state: "+err.Error())
	}
	return state, true, nil
}

func (s *FileSnapshotStore) Load(ctx context.Context, id gotato.ConversationID) (StoredState, bool, error) {
	if err := contextError(ctx); err != nil {
		return StoredState{}, false, err
	}
	path, err := s.fileName(id)
	if err != nil {
		return StoredState{}, false, err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.readLocked(path)
}

func (s *FileSnapshotStore) Delete(ctx context.Context, id gotato.ConversationID) error {
	if err := contextError(ctx); err != nil {
		return err
	}
	path, err := s.fileName(id)
	if err != nil {
		return err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return gotatoError(gotato.ErrInvalidState, "cannot delete Conversation state: "+err.Error())
	}
	return nil
}

func (s *FileSnapshotStore) List(ctx context.Context) ([]gotato.ConversationID, error) {
	if err := contextError(ctx); err != nil {
		return nil, err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	entries, err := os.ReadDir(s.dir)
	if err != nil {
		return nil, gotatoError(gotato.ErrInvalidState, "cannot list Conversation states: "+err.Error())
	}
	ids := make([]gotato.ConversationID, 0, len(entries))
	for _, item := range entries {
		if item.IsDir() {
			continue
		}
		name := item.Name()
		if !strings.HasSuffix(name, ".json") {
			continue
		}
		ids = append(ids, gotato.ConversationID(strings.TrimSuffix(name, ".json")))
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	return ids, nil
}
